[package]
name = "physics-simulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "physics_simulator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.0", features = ["abi3-py312", "extension-module"]}
