from PhysicsSimulation.Astronomy.read_in import read
from PhysicsSimulation.Astronomy.celestial_simulation import CelestialSimulation as Simulation
from PhysicsSimulation.Astronomy.celestial_body import Celestial, CelestialType